#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 <version> <github-repository> <artifact-directory> <output-formula>" >&2
  exit 2
fi

version="${1#v}"
repository="$2"
artifact_dir="$3"
output="$4"
tag="v${version}"

checksum() {
  local target="$1"
  local archive="smolbren-${tag}-${target}.tar.gz"
  local path="${artifact_dir}/${archive}"
  if [[ ! -f "$path" ]]; then
    echo "missing release archive: $path" >&2
    exit 1
  fi
  shasum -a 256 "$path" | awk '{print $1}'
}

macos_arm_sha="$(checksum aarch64-apple-darwin)"
linux_arm_sha="$(checksum aarch64-unknown-linux-gnu)"
linux_intel_sha="$(checksum x86_64-unknown-linux-gnu)"

mkdir -p "$(dirname "$output")"
cat > "$output" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by smolbren's release workflow. Do not edit manually.

class Smolbren < Formula
  desc "Ontology-first search over Markdown vaults"
  homepage "https://smolbren.com"
  version "${version}"
  license "MIT"

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/${repository}/releases/download/${tag}/smolbren-${tag}-aarch64-apple-darwin.tar.gz"
      sha256 "${macos_arm_sha}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/${repository}/releases/download/${tag}/smolbren-${tag}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm_sha}"
    end
    on_intel do
      url "https://github.com/${repository}/releases/download/${tag}/smolbren-${tag}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_intel_sha}"
    end
  end

  def install
    bin.install "smolbren"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/smolbren --version")
  end
end
EOF
